---
- hosts: laptops
  become: true
  become_method: sudo

  tasks:

    - name: apt-get update && install deps
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - wget
        - rsync
        - make
        - net-tools
      tags:
        - setup
        - deps

    - name: Ignore lid close
      lineinfile:
        path: /etc/systemd/logind.conf
        line: HandleLidSwitch=ignore
      notify:
        - restart systemd-logind service
      tags:
        - setup
        - lid

  handlers:

    - name: restart systemd-logind service
      service:
        name: systemd-logind
        state: restarted
      tags:
       - setup
       - lid
