---
- hosts: nfs-server
  become: true
  become_method: sudo
  tasks:

    - name: install nfs software
      package:
        name: nfs-kernel-server
        state: present
      tags:
        - nfs

    - name: Ensure directories to export exist
      file:
        path: "{{ item.strip().split()[0] }}"
        state: directory
      with_items: "{{ nfs_exports }}"
      notify: restart nfs
      tags:
        - nfs

    - name: Generate /etc/exports file
      template:
        src: exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: 0644
      register: nfs_exports_copy
      notify: restart nfs
      tags:
        - nfs

    - name: Ensure nfs is running
      service:
        name: nfs-server
        state: started
        enabled: yes
      when: nfs_exports|length
      tags:
        - nfs

  handlers:
    - name: restart nfs
      service:
        name: nfs-server
        state: restarted
      when: nfs_exports|length
      tags:
        - nfs

- hosts: nfs-client
  become: true
  become_method: sudo
  tasks:

    - name: Ensure directories to import exist
      file:
        path: "{{ item.strip().split()[0] }}"
        state: directory
      with_items: "{{ nfs_imports }}"
      tags:
        - nfs

    - name: install nfs software
      package:
        name: nfs-common
        state: present
      tags:
        - nfs

    - name: set mountpoints
      mount:
        name: "{{ item }}"
        src: "{{hostvars[groups['nfs-server'][0]]['ansible_default_ipv4']['address']}}:/data"
        fstype: nfs
        opts: defaults
        dump: 0
        passno: 2
        state: mounted
      with_items: "{{ nfs_imports }}"
      tags:
        - nfs
