---
- hosts: shredder
  become: true
  become_method: sudo
  vars:
    storage_driver: overlay2
    graph: /var/lib/docker
    log_driver: json-file
    log_opts:
      max_size: 10m
      max_file: 2
    debug: 'false'

  tasks:

    # Dependencies
    - name: apt-get update && install deps
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - wget
        - rsync
        - make
        - zfsutils-linux
        - htop
        - iotop
        - screen
        - lm-sensors
      tags:
        - setup
        - deps

    # Ansible
    - name: add ansible ppa
      apt_repository:
        repo: 'ppa:ansible/ansible'

    - name: apt-get update && install ansible
      apt:
        update_cache: yes
        name: ansible
        state: present

    # Docker
    # https://gist.github.com/jokla/2632d3097b38c474eedf72b973262368

    - name: configure /etc/docker/daemon.json.j2
      template:
        src: docker_daemon.json.j2
        dest: /etc/docker/daemon.json
      register: daemon_json
      notify: restart docker

    - name: Ensure directories exist
      file:
        path: "{{ docker_dir }}"
        state: directory
      when: daemon_json.changed

    - name:
      synchronize:
        src: /var/lib/docker/
        dest: "{{ docker_dir }}"
        recursive: yes
      delegate_to: "{{ inventory_hostname }}"
      when:
        - daemon_json.changed
        - graph != /var/lib/docker
      notify: restart docker

  handlers:

    - name: restart docker
      systemd:
        name: docker.service
        state: restarted
        enabled: yes
        daemon_reload: yes

