---
- hosts: all
  become: true
  become_method: sudo
  tasks:

    - name: apt-get update && install deps
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - wget
        - rsync
        - make
      tags:
        - setup
        - deps

    - name: Ignore lid close
      lineinfile:
        path: /etc/systemd/logind.conf
        line: HandleLidSwitch=ignore
      notify:
        - restart systemd-logind service
      tags:
        - setup
        - lid

  handlers:

    - name: restart systemd-logind service
      service:
        name: systemd-logind
        state: restarted
      tags:
       - setup
       - lid

    - name: update-ca-certificates
      command: /usr/sbin/update-ca-certificates



# MORE TASKS
#   - name: Ensure local certs directory exists
#     file:
#       state: directory
#       path: /usr/local/share/ca-certificates

#   - name: Install squid_https cert
#     copy:
#       src: ./squid_https.crt
#       dest: /usr/local/share/ca-certificates/squid_https.crt
#     notify: update-ca-certificates

#   - name: Generate /etc/hosts
#     template:
#       src: hosts.j2
#       dest: /etc/hosts
#       owner: root
#       group: root
#       mode: 0644
#     tags:
#       - setup
#       - hosts
