version: '3'

services:

  # https://github.com/linuxserver/docker-plex
  plex:
    image: linuxserver/plex
    environment:
      VERSION: 'latest'
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - /data/plex:/config
      - /data/movies:/data/movies
      - /data/tv:/data/tvshows
      - /data/transcode:/transcode
    deploy:
      replicas: 1
    ports:
      - '32400:32400'
      - '32400:32400/udp'
      - '32469:32469'
      - '32469:32469/udp'
      - '5353:5353/udp'
      - '1900:1900/udp'

  # https://github.com/linuxserver/docker-transmission
  transmission:
    image: linuxserver/transmission
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - /data/transmission:/config
      - /data/downloads:/downloads
      - /data/watch:/watch
    ports:
        - '9091:9091'
        - '51413:51413'
        - '51413:51413/udp'
    deploy:
      replicas: 1

  # https://github.com/linuxserver/docker-sickrage
  sickrage:
    image: linuxserver/sickrage
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - /data/sickrage:/config
      - /data/downloads:/downloads
      - /data/tv:/tv
    deploy:
      replicas: 1
    ports:
      - '8081:8081'

  # https://github.com/linuxserver/docker-couchpotato
  couchpotato:
    image: linuxserver/couchpotato
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      UMASK_SET: 022
    volumes:
      - /data/couchpotato:/config
      - /data/downloads:/downloads
      - /data/movies:/movies
    deploy:
      replicas: 1
    ports:
      - '5050:5050'

  sonarr:
    image: linuxserver/sonarr
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - /data/tv:/tv
      - /data/sonarr:/config
      - /data/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
    ports:
      - '8989:8989'

  radarr:
    image: linuxserver/radarr
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - /data/movies:/movies
      - /data/radarr:/config
      - /data/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
    ports:
      - '7878:7878'
