version: '3'

services:

  blog:
    image: ghost:1-alpine
    environment:
      url: "http://homelab.business/"
    volumes:
      - /data/ghost/content:/var/lib/ghost/content
    ports:
        - '2368:2368'
    deploy:
      replicas: 1
